// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PartiuAlmoco.Infra.Domain;

namespace PartiuAlmoco.Infra.Domain.Migrations
{
    [DbContext(typeof(PartiuAlmocoDbContext))]
    partial class PartiuAlmocoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("PartiuAlmoco.Core.Domain.Entities.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RestaurantPollId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantPollId");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("PartiuAlmoco.Core.Domain.Entities.RestaurantPollAggregate.RestaurantPoll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WinnerRestaurantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WinnerRestaurantId");

                    b.ToTable("RestaurantPolls");
                });

            modelBuilder.Entity("PartiuAlmoco.Core.Domain.Entities.RestaurantPollAggregate.RestaurantPollResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RestaurantPollId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalVotes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("WinnerRestaurantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantPollId");

                    b.HasIndex("WinnerRestaurantId");

                    b.ToTable("PollResults");
                });

            modelBuilder.Entity("PartiuAlmoco.Core.Domain.Entities.RestaurantPollAggregate.RestaurantPollVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RestaurantId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RestaurantPollId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("VoterId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("RestaurantPollId");

                    b.HasIndex("VoterId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("PartiuAlmoco.Core.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PartiuAlmoco.Core.Domain.Entities.Restaurant", b =>
                {
                    b.HasOne("PartiuAlmoco.Core.Domain.Entities.RestaurantPollAggregate.RestaurantPoll", null)
                        .WithMany("AllRestaurants")
                        .HasForeignKey("RestaurantPollId");
                });

            modelBuilder.Entity("PartiuAlmoco.Core.Domain.Entities.RestaurantPollAggregate.RestaurantPoll", b =>
                {
                    b.HasOne("PartiuAlmoco.Core.Domain.Entities.Restaurant", "WinnerRestaurant")
                        .WithMany()
                        .HasForeignKey("WinnerRestaurantId");
                });

            modelBuilder.Entity("PartiuAlmoco.Core.Domain.Entities.RestaurantPollAggregate.RestaurantPollResult", b =>
                {
                    b.HasOne("PartiuAlmoco.Core.Domain.Entities.RestaurantPollAggregate.RestaurantPoll", "RestaurantPoll")
                        .WithMany("PollResults")
                        .HasForeignKey("RestaurantPollId");

                    b.HasOne("PartiuAlmoco.Core.Domain.Entities.Restaurant", "WinnerRestaurant")
                        .WithMany()
                        .HasForeignKey("WinnerRestaurantId");
                });

            modelBuilder.Entity("PartiuAlmoco.Core.Domain.Entities.RestaurantPollAggregate.RestaurantPollVote", b =>
                {
                    b.HasOne("PartiuAlmoco.Core.Domain.Entities.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId");

                    b.HasOne("PartiuAlmoco.Core.Domain.Entities.RestaurantPollAggregate.RestaurantPoll", "RestaurantPoll")
                        .WithMany("Votes")
                        .HasForeignKey("RestaurantPollId");

                    b.HasOne("PartiuAlmoco.Core.Domain.Entities.User", "Voter")
                        .WithMany()
                        .HasForeignKey("VoterId");
                });
#pragma warning restore 612, 618
        }
    }
}
